name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Solo se ejecuta cuando hay cambios en main
  workflow_dispatch:  # Permite ejecutarlo manualmente si es necesario

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Static Files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Sube todos los archivos del repositorio

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
